apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: predictive-maintenance-api
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: predictive-maintenance-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
